[package]
name = "kisenon-quickstart-rust-sqlx"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = "0.4"
sqlx = { version = "0.9", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls-ring-webpki", "chrono"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
